#cloud-config

install:
  auto: true
  grub_options:
    extra_cmdline: config_url=https://raw.githubusercontent.com/Vonor/kairos/refs/heads/main/cloud-config.yaml
  device: auto
  poweroff: false
  reboot: true

hostname: metal-{{ trunc 4 .MachineID }}

users:
  - name: kairos
    passwd: kairos
    groups:
      - admin
    ssh_authorized_keys:
      - github:vonor

k3s:
  enabled: true
  args:
  - --disable=traefik,servicelb

cluster:
  cluster_token: randomstring
  control_plane_host: metal-{{ trunc 4 .MachineID }}
  role: init,worker
  config: |
    node-name: metal-{{ trunc 4 .MachineID }}
